import { useGLTF } from '@react-three/drei'
import { useEffect, useMemo, useState, Suspense, type ReactNode } from 'react'
import type { Object3D } from 'three'
import type { Asset } from '../types'

const alarmColor: Record<Asset['alarm_level'], string> = { normal: '#38db93', warning: '#f4b740', critical: '#ff5c60', emergency_shutdown: '#ff2530' }
function assetForObject(object: Object3D, assets: Asset[]) { let current: Object3D | null = object; while (current) { const name = current.name.toUpperCase(); const found = assets.find(asset => asset.asset_id && (name.includes(asset.asset_id.replace('-', '')) || name.includes(asset.asset_id))); if (found) return found; current = current.parent } return undefined }
function LoadedModel({ assets, selectedId, select }: { assets: Asset[]; selectedId?: string; select: (asset: Asset) => void }) { const { scene } = useGLTF('/models/chemical_plant.glb'); const model = useMemo(() => scene.clone(true), [scene]); useEffect(() => { model.traverse(node => { const asset = assetForObject(node, assets); if (!asset || !('material' in node)) return; const materials = Array.isArray(node.material) ? node.material : [node.material]; materials.forEach(material => { if ('emissive' in material && material.emissive) { material.emissive.set(alarmColor[asset.alarm_level] ?? '#38db93'); material.emissiveIntensity = asset.asset_id === selectedId ? .9 : .2 } }) }) }, [assets, model, selectedId]); return <primitive object={model} onClick={(event: { stopPropagation: () => void; object: Object3D }) => { event.stopPropagation(); const asset = assetForObject(event.object, assets); if (asset) select(asset) }} /> }
export default function PlantModel({ assets, selectedId, select, fallback }: { assets: Asset[]; selectedId?: string; select: (asset: Asset) => void; fallback: ReactNode }) { const [available, setAvailable] = useState(false); useEffect(() => { fetch('/models/chemical_plant.glb', { method: 'HEAD' }).then(response => { const ct = response.headers.get('content-type') ?? ''; setAvailable(response.ok && (ct.includes('model') || ct.includes('octet-stream'))) }).catch(() => setAvailable(false)) }, []); return available ? <Suspense fallback={<>{fallback}</>}><LoadedModel assets={assets} selectedId={selectedId} select={select} /></Suspense> : <>{fallback}</> }

