from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from ml.ingestion.common import REPO_ROOT

INPUT = REPO_ROOT / "data" / "processed" / "ai4i" / "uci-601" / "ai4i.parquet"
ASSETS = REPO_ROOT / "docs" / "eda_assets"
SUMMARY = REPO_ROOT / "docs" / "eda" / "AI4I_summary.md"


def main() -> None:
    if not INPUT.exists():
        raise FileNotFoundError(f"Missing {INPUT}; run ingestion first.")
    frame = pd.read_parquet(INPUT)
    ASSETS.mkdir(parents=True, exist_ok=True); SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    numeric = frame.select_dtypes(include="number")
    stats = numeric.describe().T
    stats.to_csv(ASSETS / "ai4i_summary_statistics.csv")
    labels = ["machine_failure", "twf", "hdf", "pwf", "osf", "rnf"]
    balance = frame[labels].sum().astype(int)
    balance.to_csv(ASSETS / "ai4i_class_balance.csv", header=["positive_count"])
    sns.set_theme(style="darkgrid")
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    sns.histplot(frame, x="tool_wear_min", hue="machine_failure", bins=35, multiple="layer", ax=axes[0])
    sns.scatterplot(data=frame.sample(min(2500, len(frame)), random_state=42), x="torque_nm", y="rotational_speed_rpm", hue="machine_failure", alpha=.65, ax=axes[1])
    fig.tight_layout(); fig.savefig(ASSETS / "ai4i_distributions.png", dpi=150); plt.close(fig)
    fig, ax = plt.subplots(figsize=(9, 7)); sns.heatmap(numeric.corr(), cmap="vlag", center=0, ax=ax); fig.tight_layout(); fig.savefig(ASSETS / "ai4i_correlation.png", dpi=150); plt.close(fig)
    fig, ax = plt.subplots(figsize=(8, 4)); balance.sort_values(ascending=False).plot.bar(ax=ax, color="#2878b5"); ax.set_ylabel("Positive records"); fig.tight_layout(); fig.savefig(ASSETS / "ai4i_class_balance.png", dpi=150); plt.close(fig)
    # Failure-mode flags are outcomes used to construct the composite label, so including
    # them here would be target leakage rather than an operational predictor observation.
    operational = ["air_temperature_k", "process_temperature_k", "rotational_speed_rpm", "torque_nm", "tool_wear_min"]
    top_corr = numeric[operational + ["machine_failure"]].corr()["machine_failure"].drop("machine_failure").abs().sort_values(ascending=False).head(3)
    SUMMARY.write_text("# AI4I EDA summary\n\n"
        "Generated by `py -m ml.eda.ai4i_eda` from the local processed UCI 601 Parquet file. This is descriptive analysis, not model performance.\n\n"
        f"* Rows processed: {len(frame):,}; null cells: {int(frame.isna().sum().sum()):,}.\n"
        f"* Machine-failure positives: {int(balance['machine_failure']):,} of {len(frame):,} ({balance['machine_failure'] / len(frame):.2%}).\n"
        "* Specific-mode positive counts: " + ", ".join(f"{name.upper()}={int(value):,}" for name, value in balance.drop("machine_failure").items()) + ".\n"
        "* Largest absolute Pearson correlations among operational numeric features and the composite label: " + ", ".join(f"`{name}`={value:.3f}" for name, value in top_corr.items()) + ". The failure-mode flags are intentionally excluded here because they construct the label and would leak it into a predictor view. Correlation is not causal evidence.\n"
        "* Figures and complete computed summary statistics are in `docs/eda_assets/`. AI4I remains synthetic data.\n", encoding="utf-8")
    print(f"Wrote AI4I EDA assets and {SUMMARY}")


if __name__ == "__main__":
    main()
