from __future__ import annotations

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from ml.ingestion.common import REPO_ROOT

INPUT = REPO_ROOT / "data" / "processed" / "tep" / "harvard-dvn-6c3jr1-v1.0" / "tep.parquet"
ASSETS = REPO_ROOT / "docs" / "eda_assets"
SUMMARY = REPO_ROOT / "docs" / "eda" / "TEP_summary.md"


def main() -> None:
    if not INPUT.exists():
        raise FileNotFoundError(f"Missing {INPUT}; run ingestion first.")
    frame = pd.read_parquet(INPUT)
    ASSETS.mkdir(parents=True, exist_ok=True); SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    sensors = [column for column in frame.columns if column.startswith("xmeas_") or column.startswith("xmv_")]
    stats = frame[sensors].describe().T
    stats.to_csv(ASSETS / "tep_summary_statistics.csv")
    balance = frame.groupby("faultnumber").size().sort_index()
    balance.to_csv(ASSETS / "tep_fault_balance.csv", header=["row_count"])
    sample = frame.sort_values(["simulationrun", "sample"]).groupby("simulationrun", group_keys=False).head(500)
    selected = sensors[:3]
    fig, axes = plt.subplots(len(selected), 1, figsize=(11, 7), sharex=True)
    for axis, feature in zip(axes, selected): axis.plot(sample["sample"], sample[feature], lw=.8); axis.set_ylabel(feature)
    axes[-1].set_xlabel("Published sample index"); fig.tight_layout(); fig.savefig(ASSETS / "tep_time_series_sample.png", dpi=150); plt.close(fig)
    fig, ax = plt.subplots(figsize=(9, 6)); sns.heatmap(frame[sensors].sample(min(50_000, len(frame)), random_state=42).corr(), cmap="vlag", center=0, ax=ax); fig.tight_layout(); fig.savefig(ASSETS / "tep_correlation.png", dpi=150); plt.close(fig)
    fig, ax = plt.subplots(figsize=(11, 4)); balance.plot.bar(ax=ax, color="#d56a3a"); ax.set_xlabel("Published fault number"); ax.set_ylabel("Rows"); fig.tight_layout(); fig.savefig(ASSETS / "tep_fault_balance.png", dpi=150); plt.close(fig)
    fault_free = int(balance.get(0, 0)); nonzero = len(frame) - fault_free
    SUMMARY.write_text("# TEP EDA summary\n\n"
        "Generated by `py -m ml.eda.tep_eda` from the local processed Harvard Dataverse v1.0 Parquet file. TEP is a process simulation, not operational plant telemetry.\n\n"
        f"* Rows processed: {len(frame):,}; sensor columns: {len(sensors)}; sensor null cells: {int(frame[sensors].isna().sum().sum()):,}.\n"
        f"* Published `faultnumber=0` rows: {fault_free:,}; non-zero fault-number rows: {nonzero:,}; distinct fault numbers: {balance.index.nunique():,}.\n"
        "* The time-series figure uses the published sample index and one deterministic run sample; it does not infer a physical sampling interval.\n"
        "* Complete computed statistics, fault counts, and figures are in `docs/eda_assets/`. Visual relationships are descriptive only and are not a trained fault model.\n", encoding="utf-8")
    print(f"Wrote TEP EDA assets and {SUMMARY}")


if __name__ == "__main__":
    main()

