import { useEffect, useState } from 'react'
import PlantScene from './PlantScene'
import type { Asset, PlantState } from './types'

const api = 'http://localhost:8000'
const risk = (value: number) => `${Math.round(value * 100)}%`
const initialState: PlantState = {
  source_kind: 'SIMULATED_INTEGRATION_BASELINE', source_notice: 'Demonstration telemetry is shown until the API connects.', generated_at: new Date().toISOString(),
  assets: [
    { asset_id: 'TK-101', asset_name: 'Feed Tank', temperature_c: 45.7, pressure_bar: 4.12, level_percent: 66.4, flow_m3h: 81.9, valve_open: true, gas_ppm: 4.0, risk_score: .18, alarm_level: 'normal', updated_at: new Date().toISOString() },
    { asset_id: 'RX-201', asset_name: 'Reactor', temperature_c: 65.1, pressure_bar: 31.05, level_percent: 62.38, flow_m3h: 46.99, valve_open: true, gas_ppm: 11.0, risk_score: .72, alarm_level: 'critical', updated_at: new Date().toISOString() },
    { asset_id: 'TK-301', asset_name: 'Buffer Tank', temperature_c: 54.0, pressure_bar: 3.4, level_percent: 42.0, flow_m3h: 55.0, valve_open: false, gas_ppm: 3.0, risk_score: .42, alarm_level: 'warning', updated_at: new Date().toISOString() },
  ],
}
export default function App() { const [state, setState] = useState<PlantState>(initialState), [selected, setSelected] = useState<Asset | null>(null), [connection, setConnection] = useState('DEMO MODE'); useEffect(() => { fetch(`${api}/api/v1/plant/state`).then(r => r.json()).then(setState).catch(() => setConnection('DEMO MODE')); const socket = new WebSocket('ws://localhost:8000/ws/telemetry'); socket.onopen = () => setConnection('LIVE'); socket.onmessage = event => setState(JSON.parse(event.data)); socket.onerror = () => setConnection('DEMO MODE'); return () => socket.close() }, []); const current = selected ?? state.assets[1]; return <main className="twin-shell"><div className="twin-topbar"><div><p>SENTINELTWIN</p><h1>CHEMICAL PROCESS DIGITAL TWIN</h1></div><div className={`live-state ${connection === 'LIVE' ? 'live' : ''}`}><i /> {connection}</div></div><PlantScene assets={state.assets} select={setSelected} /><div className="scene-caption">INTERACTIVE PROCESS OVERVIEW <span>Drag to orbit · Scroll to zoom · Select equipment for live telemetry</span></div><aside className="floating-inspector"><div className="inspector-head"><p>SELECTED EQUIPMENT</p><b>{current.asset_name}</b><span>{current.asset_id}</span></div><div className={`status-pill ${current.alarm_level}`}>{current.alarm_level.replace('_', ' ')}</div><div className="stat-grid"><div><small>TEMPERATURE</small><strong>{current.temperature_c} <em>°C</em></strong></div><div><small>PRESSURE</small><strong>{current.pressure_bar} <em>bar</em></strong></div><div><small>LEVEL</small><strong>{current.level_percent}<em>%</em></strong></div><div><small>DEMO RISK</small><strong>{risk(current.risk_score)}</strong></div></div><p className="baseline-note">Synthetic integration telemetry. Not a safety-limit or ML prediction.</p></aside><div className="asset-strip">{state.assets.map(asset => <button key={asset.asset_id} className={asset.asset_id === current.asset_id ? 'selected' : ''} onClick={() => setSelected(asset)}><i className={asset.alarm_level} />{asset.asset_id}<span>{asset.asset_name}</span></button>)}</div></main> }
