import { Canvas, useFrame } from '@react-three/fiber'
import { Html, OrbitControls, Text } from '@react-three/drei'
import { useMemo, useRef, type ReactNode } from 'react'
import { Quaternion, Vector3, type Group } from 'three'
import type { Asset } from './types'

type Vec = [number, number, number]
type EquipmentProps = { asset?: Asset; name: string; position: Vec; onSelect: () => void; children: ReactNode; labelOffset?: Vec }
const stateColor: Record<Asset['alarm_level'], string> = { normal: '#38db93', warning: '#f4b740', critical: '#ff5c60', emergency_shutdown: '#f23e46' }
const steel = '#a9b5b9', darkSteel = '#4f636d', safety = '#d39c29', processGreen = '#18e388'

function Pipe({ from, to, radius = .09 }: { from: Vec; to: Vec; radius?: number }) {
  const { midpoint, length, rotation } = useMemo(() => { const start = new Vector3(...from), end = new Vector3(...to), delta = end.clone().sub(start), axis = new Vector3(0, 1, 0); return { midpoint: start.add(end).multiplyScalar(.5), length: delta.length(), rotation: new Quaternion().setFromUnitVectors(axis, delta.normalize()) } }, [from, to])
  return <mesh position={midpoint} quaternion={rotation} castShadow><cylinderGeometry args={[radius, radius, length, 14]} /><meshStandardMaterial color={steel} metalness={.82} roughness={.2} /></mesh>
}
function PipeRun({ points, radius }: { points: Vec[]; radius?: number }) { return <group>{points.slice(1).map((point, index) => <Pipe key={index} from={points[index]} to={point} radius={radius} />)}{points.slice(1, -1).map((point, index) => <mesh key={`bend-${index}`} position={point}><sphereGeometry args={[(radius ?? .09) * 1.08, 12, 12]} /><meshStandardMaterial color={steel} metalness={.82} /></mesh>)}</group> }
function Base({ width = 2.2, depth = 2.2 }: { width?: number; depth?: number }) { return <group><mesh position={[0, .04, 0]} receiveShadow><boxGeometry args={[width, .18, depth]} /><meshStandardMaterial color="#536973" metalness={.65} /></mesh><mesh position={[0, -.07, 0]}><boxGeometry args={[width + .25, .08, depth + .25]} /><meshStandardMaterial color="#c1c9ca" /></mesh></group> }
function Rail({ position, width = 1.8, depth = 1.7 }: { position: Vec; width?: number; depth?: number }) { const z = [-depth / 2, depth / 2], x = [-width / 2, width / 2]; return <group position={position}>{x.flatMap((xv, i) => z.map((zv, j) => <mesh key={`${i}-${j}`} position={[xv, .45, zv]}><cylinderGeometry args={[.027, .027, .9, 8]} /><meshStandardMaterial color={safety} /></mesh>))}<Pipe from={[-width / 2, .85, -depth / 2]} to={[width / 2, .85, -depth / 2]} radius={.027} /><Pipe from={[-width / 2, .85, depth / 2]} to={[width / 2, .85, depth / 2]} radius={.027} /></group> }
function Ladder({ position, height }: { position: Vec; height: number }) { const rungs = Array.from({ length: Math.floor(height / .28) }, (_, i) => i); return <group position={position}><mesh position={[-.19, height / 2, 0]}><cylinderGeometry args={[.028, .028, height, 8]} /><meshStandardMaterial color={safety} /></mesh><mesh position={[.19, height / 2, 0]}><cylinderGeometry args={[.028, .028, height, 8]} /><meshStandardMaterial color={safety} /></mesh>{rungs.map(i => <mesh key={i} position={[0, .15 + i * .28, 0]} rotation={[0, 0, Math.PI / 2]}><cylinderGeometry args={[.022, .022, .38, 8]} /><meshStandardMaterial color={safety} /></mesh>)}</group> }
function StatusLabel({ asset, title, position, onSelect }: { asset?: Asset; title: string; position: Vec; onSelect: () => void }) { if (!asset) return <Text position={position} fontSize={.22} color="#17222b">{title}</Text>; const color = stateColor[asset.alarm_level]; return <Html position={position} distanceFactor={12} center><button className="telemetry-tag" onClick={onSelect}><b>{title}</b><span style={{ color }}>● {asset.alarm_level.replace('_', ' ')}</span><small>T = {asset.temperature_c} °C&nbsp;&nbsp; P = {asset.pressure_bar} bar</small></button></Html> }
function Equipment({ asset, name, position, onSelect, children, labelOffset = [0, 3.1, 0] }: EquipmentProps) { const ref = useRef<Group>(null); const critical = asset?.alarm_level === 'critical' || asset?.alarm_level === 'emergency_shutdown'; useFrame(({ clock }) => { if (ref.current) ref.current.scale.setScalar(critical ? 1 + Math.sin(clock.elapsedTime * 4) * .012 : 1) }); return <group ref={ref} position={position} onClick={event => { event.stopPropagation(); onSelect() }}>{children}<StatusLabel asset={asset} title={name} position={labelOffset} onSelect={onSelect} /></group> }
function ProcessFill({ asset, height, radius, y = 0 }: { asset?: Asset; height: number; radius: number; y?: number }) { const fill = (asset?.level_percent ?? 60) / 100; return <mesh position={[0, y - height * (1 - fill) / 2, 0]} scale={[1, fill, 1]}><cylinderGeometry args={[radius, radius, height, 32]} /><meshStandardMaterial color={processGreen} emissive="#0ca95d" emissiveIntensity={1.35} transparent opacity={.68} /></mesh> }
function Reactor({ asset, position, onSelect }: { asset?: Asset; position: Vec; onSelect: () => void }) { return <Equipment asset={asset} name="Reactor R-101" position={position} onSelect={onSelect} labelOffset={[0, 4.25, 0]}><Base width={2.15} depth={2.15} /><mesh position={[0, 1.55, 0]}><boxGeometry args={[1.48, 3.0, 1.25]} /><meshStandardMaterial color="#73949a" metalness={.35} transparent opacity={.4} /></mesh><ProcessFill asset={asset} height={2.65} radius={.62} y={1.53} /><mesh position={[0, 3.12, 0]}><sphereGeometry args={[.76, 26, 14]} /><meshStandardMaterial color="#9caeb1" metalness={.65} transparent opacity={.55} /></mesh>{[-.56, .56].map(x => <mesh key={x} position={[x, 1.55, .67]}><cylinderGeometry args={[.04, .04, 3.0, 8]} /><meshStandardMaterial color={safety} /></mesh>)}<Ladder position={[.94, .18, .72]} height={3.05} /><Rail position={[0, 3.1, 0]} width={1.7} depth={1.55} /><PipeRun points={[[-.45, 3.55, 0], [-.45, 4.08, 0], [.45, 4.08, 0], [.45, 3.55, 0]]} radius={.07} /></Equipment> }
function Column({ asset, position, onSelect }: { asset?: Asset; position: Vec; onSelect: () => void }) { return <Equipment asset={asset} name="Stripper C-101" position={position} onSelect={onSelect} labelOffset={[0, 5.7, 0]}><Base width={2.25} depth={2.25} /><mesh position={[0, 2.5, 0]}><cylinderGeometry args={[.72, .72, 5, 40]} /><meshStandardMaterial color="#b9c7c7" metalness={.74} transparent opacity={.47} /></mesh><ProcessFill asset={asset} height={4.45} radius={.59} y={2.5} />{[.7, 1.55, 2.4, 3.25, 4.1].map(y => <group key={y}><mesh position={[0, y, 0]}><cylinderGeometry args={[.76, .76, .07, 32]} /><meshStandardMaterial color="#dfe7e7" metalness={.7} /></mesh><mesh position={[0, y + .04, 0]} rotation={[Math.PI / 2, 0, 0]}><torusGeometry args={[.73, .035, 8, 36]} /><meshStandardMaterial color={safety} /></mesh></group>)}<mesh position={[0, 5.05, 0]}><sphereGeometry args={[.72, 30, 16]} /><meshStandardMaterial color="#bac7c7" metalness={.75} /></mesh><Ladder position={[-1.02, .1, .35]} height={5.05} /><Rail position={[0, 4.7, 0]} width={1.8} depth={1.8} /></Equipment> }
function Separator({ asset, position, onSelect }: { asset?: Asset; position: Vec; onSelect: () => void }) { return <Equipment asset={asset} name="Separator V-201" position={position} onSelect={onSelect} labelOffset={[0, 3.75, 0]}><Base width={1.9} depth={1.9} /><mesh position={[0, 1.4, 0]}><cylinderGeometry args={[.57, .57, 2.8, 36]} /><meshStandardMaterial color="#a8b9b9" metalness={.7} transparent opacity={.45} /></mesh><ProcessFill asset={asset} height={2.3} radius={.47} y={1.35} /><mesh position={[0, 2.84, 0]}><sphereGeometry args={[.57, 28, 14]} /><meshStandardMaterial color="#a8b9b9" metalness={.7} /></mesh><Ladder position={[.8, .1, .2]} height={2.85} /></Equipment> }
function Tank({ asset, position, onSelect }: { asset?: Asset; position: Vec; onSelect: () => void }) { return <Equipment asset={asset} name="Product tank T-301" position={position} onSelect={onSelect} labelOffset={[0, 3.65, 0]}><Base width={2.55} depth={2.55} /><mesh position={[0, 1.35, 0]}><cylinderGeometry args={[1.03, 1.03, 2.7, 40]} /><meshStandardMaterial color="#c4cccc" metalness={.65} transparent opacity={.48} /></mesh><ProcessFill asset={asset} height={2.3} radius={.92} y={1.34} />{[.52, 1.35, 2.16].map(y => <mesh key={y} position={[0, y, 1.04]} rotation={[Math.PI / 2, 0, 0]}><torusGeometry args={[1.04, .032, 8, 40]} /><meshStandardMaterial color={safety} /></mesh>)}<mesh position={[0, 2.75, 0]}><sphereGeometry args={[1.03, 32, 16]} /><meshStandardMaterial color="#c4cccc" metalness={.65} /></mesh><Ladder position={[-1.34, .08, .2]} height={2.7} /></Equipment> }
function Exchanger({ position }: { position: Vec }) { return <group position={position}><Base width={2.55} depth={1.25} /><mesh position={[0, .9, 0]} rotation={[0, 0, Math.PI / 2]}><cylinderGeometry args={[.46, .46, 2.15, 32]} /><meshStandardMaterial color={darkSteel} metalness={.78} /></mesh>{[-.82, -.41, 0, .41, .82].map(x => <mesh key={x} position={[x, .9, 0]} rotation={[0, Math.PI / 2, 0]}><torusGeometry args={[.47, .035, 8, 32]} /><meshStandardMaterial color={safety} /></mesh>)}<Text position={[0, 1.6, 0]} fontSize={.22} color="#1f303b">Condenser E-101</Text></group> }
function Pump({ asset, position, onSelect }: { asset?: Asset; position: Vec; onSelect: () => void }) { const color = asset ? stateColor[asset.alarm_level] : '#1e82c3'; return <Equipment asset={asset} name="Product pump P-201" position={position} onSelect={onSelect} labelOffset={[0, 1.85, 0]}><Base width={1.9} depth={1.35} /><mesh position={[-.25, .48, 0]} rotation={[0, 0, Math.PI / 2]}><cylinderGeometry args={[.42, .42, .92, 28]} /><meshStandardMaterial color="#1682c4" metalness={.68} /></mesh><mesh position={[.5, .48, 0]}><cylinderGeometry args={[.24, .24, .56, 24]} /><meshStandardMaterial color="#4a6270" metalness={.75} /></mesh><mesh position={[-.7, .48, 0]}><sphereGeometry args={[.4, 24, 18]} /><meshStandardMaterial color={color} emissive={color} emissiveIntensity={.42} /></mesh></Equipment> }
function InletSkid({ position }: { position: Vec }) { return <group position={position}><Base width={1.75} depth={1.25} /><mesh position={[-.18, .53, 0]} rotation={[0, 0, Math.PI / 2]}><cylinderGeometry args={[.3, .3, 1.0, 24]} /><meshStandardMaterial color="#b99c4b" metalness={.72} /></mesh><mesh position={[.56, .45, 0]}><boxGeometry args={[.35, .5, .55]} /><meshStandardMaterial color="#5d7180" metalness={.72} /></mesh><Text position={[0, 1.25, 0]} fontSize={.2} color="#253540">Inlet gases A–E</Text></group> }
function Plant({ assets, select }: { assets: Asset[]; select: (asset: Asset) => void }) { const find = (id: string) => assets.find(asset => asset.asset_id === id), feed = find('TK-101'), reactor = find('RX-201'), product = find('TK-301'), choose = (asset?: Asset) => () => asset && select(asset); return <group><InletSkid position={[-7.5, 0, .2]} /><Reactor asset={reactor} position={[-4.65, 0, .15]} onSelect={choose(reactor)} /><Exchanger position={[-1.9, 0, .1]} /><Column asset={feed} position={[1.15, 0, .15]} onSelect={choose(feed)} /><Separator asset={product} position={[4.25, 0, .65]} onSelect={choose(product)} /><Pump asset={product} position={[5.6, 0, -1.9]} onSelect={choose(product)} /><Tank asset={feed} position={[7.85, 0, .45]} onSelect={choose(feed)} />
  <PipeRun points={[[-6.7, .65, .2], [-5.95, .65, .2], [-5.95, 1.2, .2], [-5.4, 1.2, .2]]} /><PipeRun points={[[-3.85, 1.35, .15], [-2.9, 1.35, .15], [-2.9, .95, .15], [-2.55, .95, .15]]} /><PipeRun points={[[-1.25, .95, .15], [0.25, .95, .15], [0.25, 1.7, .15], [.43, 1.7, .15]]} /><PipeRun points={[[1.9, 3.8, .15], [3.25, 3.8, .15], [3.25, 2.25, .65], [3.68, 2.25, .65]]} /><PipeRun points={[[4.82, 1.2, .65], [5.6, 1.2, .65], [5.6, .95, -1.45]]} /><PipeRun points={[[6.2, .72, -1.9], [6.9, .72, -1.9], [6.9, 1.2, .45], [6.82, 1.2, .45]]} /></group> }
export default function PlantScene({ assets, select }: { assets: Asset[]; select: (asset: Asset) => void }) { return <div className="plant-scene"><Canvas shadows camera={{ position: [13.5, 8.6, 16], fov: 42 }}><color attach="background" args={['#d4dde0']} /><fog attach="fog" args={['#d4dde0', 19, 34]} /><ambientLight intensity={1.45} /><directionalLight castShadow position={[8, 15, 9]} intensity={2.35} shadow-mapSize={[2048, 2048]} /><gridHelper args={[28, 28, '#96b1b8', '#e5edef']} position={[0, -.11, 0]} /><mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -.14, 0]} receiveShadow><planeGeometry args={[30, 18]} /><meshStandardMaterial color="#e4ebed" /></mesh><Plant assets={assets} select={select} /><OrbitControls makeDefault target={[.75, 1.75, 0]} minDistance={10} maxDistance={28} maxPolarAngle={Math.PI / 2.1} /></Canvas></div> }
