import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import PressureChart from './PressureChart'
import LabSnapshotReport from './LabSnapshotReport'
import type { Asset, DashboardMode, LabAsset, LabFrame, LabOptions, LabSnapshot } from './types'
import './lab.css'

const PlantScene = lazy(() => import('./PlantScene'))

const display = (value: number | null, digits = 1) => value == null ? 'N/A' : value.toFixed(digits)
const visualAsset = (asset: LabAsset): Asset => ({ ...asset, temperature_c: asset.temperature_c ?? 0,
  pressure_bar: asset.pressure_bar ?? 0, level_percent: asset.level_percent ?? 0,
  flow_m3h: null, valve_open: null, gas_ppm: null, risk_score: null })

function LabMap({ assets, selectedId, select, highlight, playing }: { assets: LabAsset[]; selectedId: string; select: (id: string) => void; highlight: string | null; playing: boolean }) {
  return <div className={`process-map lab-process-map ${playing ? 'is-playing' : ''}`}><div className="map-topline"><span className="tiny-heading">COUPLED SYNTHETIC PROCESS ROUTE</span><span className="map-key"><i /> Generated flow</span></div><div className="process-route"><span className="route-boundary">FEED</span>{assets.map((asset, index) => <div className="route-unit" key={asset.asset_id}>{index > 0 && <div className="route-connector" aria-hidden="true"><span className="flow-pulse" /><b>→</b></div>}<button type="button" className={`equipment-node ${selectedId === asset.asset_id ? 'active' : ''} ${highlight === asset.asset_id ? 'forecast-warning' : ''}`} onClick={() => select(asset.asset_id)}><span className="node-head"><span className="node-icon">{asset.level_percent != null && <span className="node-liquid" style={{ height: `${Math.max(0, Math.min(100, asset.level_percent))}%` }} />}</span><span><strong>{asset.asset_name}</strong><small>{asset.asset_id}</small></span></span><span className="node-divider" /><span className="node-reading"><span>PRESSURE</span><b>{display(asset.pressure_bar, 2)} <small>bar</small></b></span><span className="node-reading"><span>TEMPERATURE</span><b>{display(asset.temperature_c)} <small>°C</small></b></span><span className="node-reading"><span>LEVEL</span><b>{display(asset.level_percent)} <small>{asset.level_percent == null ? '' : '%'}</small></b></span><span className="node-reading"><span>{asset.performance_percent != null ? 'PERFORMANCE' : asset.work_kw != null ? 'WORK' : 'FLOW'}</span><b>{display(asset.performance_percent ?? asset.work_kw ?? asset.flow_value)} <small>{asset.performance_percent != null ? '%' : asset.work_kw != null ? 'kW' : asset.flow_unit}</small></b></span><span className="node-state">{highlight === asset.asset_id ? 'Validated synthetic warning ≤1 h' : 'Generated telemetry'}</span></button></div>)}<span className="route-boundary">PRODUCT</span></div></div>
}

export default function PrognosisLab({ setMode }: { setMode: (mode: DashboardMode) => void }) {
  const [options, setOptions] = useState<LabOptions | null>(null), [run, setRun] = useState(0), [sample, setSample] = useState(21)
  const [frame, setFrame] = useState<LabFrame | null>(null), [playing, setPlaying] = useState(false), [speed, setSpeed] = useState(1)
  const [view, setView] = useState<'3d' | 'map'>('3d'), [selectedId, setSelectedId] = useState('RX-201')
  const [loading, setLoading] = useState(false), [error, setError] = useState<string | null>(null), [retry, setRetry] = useState(0)
  const [snapshot, setSnapshot] = useState<LabSnapshot | null>(null), [exporting, setExporting] = useState(false)
  const exportRequest = useRef<AbortController | null>(null)
  useEffect(() => { document.title = 'Equipment prognosis lab | SentinelTwin' }, [])
  useEffect(() => { const controller = new AbortController(); fetch('/api/v1/prognosis-lab/options', { signal: controller.signal }).then(async response => { if (!response.ok) throw new Error(`Options API ${response.status}`); return response.json() as Promise<LabOptions> }).then(value => { if (controller.signal.aborted || value.source_kind !== 'SYNTHETIC_EQUIPMENT_PROGNOSIS' || !value.runs.length) return; setOptions(value); const first = value.runs[0]; setRun(first.id); setSample(Math.max(21, first.samples - 15)); setError(null) }).catch(value => { if (!controller.signal.aborted) setError(`Prognosis lab unavailable: ${String(value)}`) }); return () => controller.abort() }, [retry])
  const current = options?.runs.find(item => item.id === run), total = current?.samples ?? 1
  useEffect(() => { exportRequest.current?.abort(); exportRequest.current = null; setSnapshot(null); setExporting(false); if (!run || !current) return; const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 15000); setLoading(true); fetch(`/api/v1/prognosis-lab/frame?run=${run}&sample=${sample}&points=90`, { signal: controller.signal }).then(async response => { if (!response.ok) throw new Error(`Frame API ${response.status}`); return response.json() as Promise<LabFrame> }).then(value => { if (controller.signal.aborted) return; if (value.state.source_kind !== 'SYNTHETIC_EQUIPMENT_PROGNOSIS' || value.state.run_id !== run || value.state.sample_index !== sample || value.history.run_id !== run || value.history.end_sample !== sample) throw new Error('Mismatched prognosis frame'); setFrame(value); setError(null); setLoading(false) }).catch(value => { if (!controller.signal.aborted) { setError(String(value)); setPlaying(false); setLoading(false) } }).finally(() => window.clearTimeout(timeout)); return () => { window.clearTimeout(timeout); controller.abort() } }, [run, sample, current, retry])
  const state = frame?.state.run_id === run ? frame.state : null, committed = state?.sample_index === sample
  useEffect(() => { if (!playing || !committed || loading || error) return; if (sample >= total) { setPlaying(false); return } const timer = window.setTimeout(() => setSample(value => value + 1), 2000 / speed); return () => window.clearTimeout(timer) }, [playing, committed, loading, error, sample, total, speed])
  function changeRun(value: number) { const selected = options?.runs.find(item => item.id === value); if (!selected) return; setPlaying(false); setFrame(null); setRun(value); setSample(Math.max(21, selected.samples - 15)) }
  function toggle() { if (playing) { setPlaying(false); if (state) setSample(state.sample_index) } else { if (sample >= total) setSample(21); setPlaying(true) } }
  async function exportSnapshot() { if (!state || exporting) return; setPlaying(false); setExporting(true); const controller = new AbortController(); exportRequest.current = controller; try { const response = await fetch(`/api/v1/report?source=prognosis_lab&run=${state.run_id}&sample=${state.sample_index}`, { signal: controller.signal }); if (!response.ok) throw new Error(`Report API ${response.status}`); const value = await response.json() as LabSnapshot; if (!controller.signal.aborted && exportRequest.current === controller && value.state.run_id === state.run_id && value.state.sample_index === state.sample_index) setSnapshot(value) } catch (value) { if (!controller.signal.aborted) setError(String(value)) } finally { if (exportRequest.current === controller) { exportRequest.current = null; setExporting(false) } } }
  const assets = state?.assets ?? [], selected = assets.find(asset => asset.asset_id === selectedId) ?? assets[0], prediction = state?.prognosis
  const observed = frame?.history.points.map(point => ({ minute: point.time_minutes, pressure: point.reactor_pressure_bar })) ?? []
  return <main className="dashboard dataset-dashboard rtf-dashboard lab-dashboard"><header className="site-header"><div className="brand"><span className="brand-mark">◇</span><div><span className="brand-name">SENTINELTWIN</span><span className="brand-sub">EQUIPMENT PROGNOSIS LAB</span></div></div><nav className="source-tabs" aria-label="Dataset"><button onClick={() => setMode('tep')}>TEP process</button><button onClick={() => setMode('ai4i')}>AI4I</button><button onClick={() => setMode('rtf')}>TEP RTF</button><button className="active" aria-current="page">Prognosis lab</button></nav><span className={`connection-pill ${error ? 'offline' : ''}`}><i />{error ? 'Lab unavailable' : options ? 'Synthetic lab ready' : 'Loading lab'}</span></header>
    <section className="dataset-heading"><div><span className="eyebrow">LABELLED DYNAMIC SURROGATE / RESEARCH ONLY</span><h1>Equipment prognosis lab</h1><p>Predict the next generated equipment terminal condition and remaining simulated time across five coupled units.</p></div><div className="dataset-source-indicator"><strong>1,200 runs</strong><span>Synthetic labels · no plant control</span></div></section><div className="source-banner lab-source"><span className="source-badge">SYNTHETIC, NOT OFFICIAL RTF</span><span>{state?.source_notice ?? options?.source_notice}</span></div>{error && <div className="error-banner" role="alert"><span>{error}</span><button className="control-button" onClick={() => setRetry(value => value + 1)}>Retry</button></div>}
    <section className="dataset-controls"><label>RUN<select value={run} onChange={event => changeRun(Number(event.target.value))}>{options?.runs.map(item => <option key={item.id} value={item.id}>{item.id} · {item.samples} samples</option>)}</select></label><label>PLAYBACK SPEED<select value={speed} onChange={event => setSpeed(Number(event.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label><button className="control-button" onClick={toggle} disabled={!state || !!error}>{playing ? 'Pause stream' : sample >= total ? 'Restart stream' : 'Play stream'}</button><div className="sample-control"><label htmlFor="lab-sample">SAMPLE <strong>{sample} / {total}</strong></label><input id="lab-sample" type="range" min="1" max={total} value={Math.min(sample, total)} onChange={event => { setPlaying(false); setSample(Number(event.target.value)) }} /></div></section>
    <section className={`playback-status ${playing && committed && !loading ? 'is-playing' : ''}`} data-run={state?.run_id ?? ''} data-sample={state?.sample_index ?? ''}><div><i /><strong>{playing ? 'Synthetic trajectory playing' : 'Synthetic trajectory paused'}</strong><span>{state ? `Run ${state.run_id} · ${state.time_minutes} simulated min` : 'Waiting for data'}</span></div><span>{loading && state ? 'Loading next sample; committed frame remains visible' : '3-minute generated cadence'}</span></section>
    <section className="summary-strip"><div><span>FAILURE ≤60 MIN</span><strong>{prediction?.failure_within_horizon_probability == null ? 'Unavailable' : `${(prediction.failure_within_horizon_probability * 100).toFixed(1)}%`}</strong><small>Validation-thresholded model score</small></div><div><span>ESTIMATED RUL</span><strong>{prediction?.remaining_minutes == null ? 'Abstained' : `${prediction.remaining_minutes.toFixed(1)} min`}</strong><small>Generated time only</small></div><div><span>NEXT EQUIPMENT</span><strong>{prediction?.predicted_equipment_id ?? 'Abstained'}</strong><small>{prediction?.confidence == null ? 'No equipment claim' : `${(prediction.confidence * 100).toFixed(1)}% model confidence`}</small></div><div><span>FAILURE MODE</span><strong>{prediction?.predicted_failure_mode?.replace(/_/g, ' ') ?? 'Unassessed'}</strong><small>Ten injected modes</small></div></section>
    {prediction && <div className={`rtf-forecast-note ${prediction.highlight_equipment_id ? 'has-warning' : ''}`} role="status"><strong>{prediction.highlight_equipment_id ? `${prediction.highlight_equipment_id} synthetic warning` : prediction.unit_status === 'abstained' ? 'Model abstained' : 'Equipment unassessed'}</strong><span>{prediction.notice}</span></div>}{state?.observed_outcome && <div className="lab-outcome" role="status"><strong>Observed synthetic outcome:</strong> {state.observed_outcome.censored ? 'healthy/censored completion' : `${state.observed_outcome.failed_equipment_id} · ${state.observed_outcome.failure_mode?.replace(/_/g, ' ')}`}</div>}
    <div className="snapshot-actions"><a className="rtf-evaluation-link" href="/?evaluation=equipment-prognosis" target="_blank" rel="noreferrer">Model evaluation ↗</a><button className="control-button" onClick={exportSnapshot} disabled={!state || exporting}>{exporting ? 'Preparing snapshot…' : 'Export displayed snapshot'}</button></div>
    <section className="main-layout"><div className="visual-card"><div className="section-title"><div><span className="tiny-heading">FIVE-UNIT TOPOLOGY</span><h2>Generated telemetry and warning target</h2></div><div className="view-tabs"><button className={view === '3d' ? 'active' : ''} onClick={() => setView('3d')}>3D plant</button><button className={view === 'map' ? 'active' : ''} onClick={() => setView('map')}>2D flow</button></div></div>{view === '3d' ? <Suspense fallback={<div className="scene scene-loading">Loading 3D view…</div>}><PlantScene assets={assets.map(visualAsset)} selectedId={selected?.asset_id ?? null} select={asset => setSelectedId(asset.asset_id)} playing={playing && !!state && !loading} speed={speed} highlightUnitId={prediction?.highlight_equipment_id} /></Suspense> : <LabMap assets={assets} selectedId={selected?.asset_id ?? ''} select={setSelectedId} highlight={prediction?.highlight_equipment_id ?? null} playing={playing} />}</div><aside className="inspector-card"><span className="tiny-heading">SELECTED GENERATED UNIT</span>{selected && <><div className="inspector-head"><div><h2>{selected.asset_name}</h2><span>{selected.asset_id}</span></div><span className={`status-chip ${prediction?.highlight_equipment_id === selected.asset_id ? 'forecast-warning' : ''}`}>{prediction?.highlight_equipment_id === selected.asset_id ? 'PREDICTED ≤1 H' : 'UNASSESSED'}</span></div><div className="metric-grid"><div><span>TEMPERATURE</span><strong>{display(selected.temperature_c)} <small>°C</small></strong></div><div><span>PRESSURE</span><strong>{display(selected.pressure_bar, 2)} <small>bar</small></strong></div><div><span>LEVEL</span><strong>{display(selected.level_percent)} <small>{selected.level_percent == null ? '' : '%'}</small></strong></div><div><span>FLOW / PERFORMANCE</span><strong>{display(selected.performance_percent ?? selected.work_kw ?? selected.flow_value)} <small>{selected.performance_percent != null ? '%' : selected.work_kw != null ? 'kW' : selected.flow_unit}</small></strong></div></div><div className="inspector-note"><strong>INTERPRETATION</strong><p>Readings and labels are generated by the documented surrogate. N/A means that metric does not physically apply to this equipment representation.</p></div></>}</aside></section>
    <section className="analysis-layout">{observed.length > 0 && <PressureChart title="Generated reactor pressure" caption="Past and current generated samples only; no future truth is included in model features." observed={observed} projected={[]} />}<section className="explanation-card"><span className="tiny-heading">MODEL BOUNDARY</span><h2>A validated synthetic benchmark—not a plant alarm</h2><p>The terminal equipment and failure mode are known because this lab injects them. The official TEP RTF view remains separate and does not inherit these labels.</p></section></section><footer><span>SentinelTwin · equipment prognosis lab</span><span>Dynamic-surrogate evidence only · no safety actuation</span></footer>{snapshot && <LabSnapshotReport report={snapshot} onClose={() => setSnapshot(null)} />}
  </main>
}
